//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation_Rules_Kafedra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calculation_Rules_Kafedra()
        {
            this.Calculation_Rules_Facility = new HashSet<Calculation_Rules_Facility>();
        }
    
        public int Id { get; set; }
        public byte TypeOfOperating { get; set; }
        public int Id_Criteria { get; set; }
        public int Id_Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculation_Rules_Facility> Calculation_Rules_Facility { get; set; }
        public virtual Category_Kafedra Category_Kafedra { get; set; }
        public virtual Сriteria_Teachers Сriteria_Teachers { get; set; }
    }
}
