//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation_Rules_Facility
    {
        public int Id { get; set; }
        public byte TypeOfOperating { get; set; }
        public Nullable<int> Id_Criteria { get; set; }
        public int Id_Category { get; set; }
        public Nullable<int> Id_Calculation_Rule_Kafedra { get; set; }
    
        public virtual Calculation_Rules_Kafedra Calculation_Rules_Kafedra { get; set; }
        public virtual Category_Facility Category_Facility { get; set; }
        public virtual Criteria_Kafedra Criteria_Kafedra { get; set; }
    }
}
