//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category_Facility()
        {
            this.Calculation_Rules_Facility = new HashSet<Calculation_Rules_Facility>();
            this.Criteria_Facility = new HashSet<Criteria_Facility>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_block { get; set; }
    
        public virtual Block_Facility Block_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculation_Rules_Facility> Calculation_Rules_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Criteria_Facility> Criteria_Facility { get; set; }
    }
}
