//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria_Kafedra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criteria_Kafedra()
        {
            this.Calculation_Rules_Facility = new HashSet<Calculation_Rules_Facility>();
            this.Mark_Kafedra = new HashSet<Mark_Kafedra>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> Id_Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculation_Rules_Facility> Calculation_Rules_Facility { get; set; }
        public virtual Category_Kafedra Category_Kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark_Kafedra> Mark_Kafedra { get; set; }
    }
}
