//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria_Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criteria_Facility()
        {
            this.Mark_Facility = new HashSet<Mark_Facility>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> Id_Category { get; set; }
    
        public virtual Category_Facility Category_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark_Facility> Mark_Facility { get; set; }
    }
}
