//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facility()
        {
            this.Kafedras = new HashSet<Kafedra>();
            this.Mark_Facility = new HashSet<Mark_Facility>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public Nullable<int> Id_TeacherDecan { get; set; }
        public string SName { get; set; }
        public int MarkB1 { get; set; }
        public int MarkB2 { get; set; }
        public int MarkB3 { get; set; }
        public int MarkB4 { get; set; }
        public int MarkB5 { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kafedra> Kafedras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark_Facility> Mark_Facility { get; set; }
    }
}
