//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkTeachersCheck
    {
        public int Id { get; set; }
        public int Id_Comission { get; set; }
        public int Id_MarkTeacher { get; set; }
        public int oldStatus { get; set; }
        public int newStatus { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual Comission Comission { get; set; }
        public virtual Mark_Teachers Mark_Teachers { get; set; }
    }
}
