//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark_Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mark_Facility()
        {
            this.Status_Doc_Facility = new HashSet<Status_Doc_Facility>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Facility { get; set; }
        public Nullable<int> Id_Criteria { get; set; }
        public Nullable<int> Kolvo_ed { get; set; }
        public Nullable<int> Status { get; set; }
        public int Kolvo_mark { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Criteria_Facility Criteria_Facility { get; set; }
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_Doc_Facility> Status_Doc_Facility { get; set; }
    }
}
