//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityRatingEntities8 : DbContext
    {
        public UniversityRatingEntities8()
            : base("name=UniversityRatingEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block_Facility> Block_Facility { get; set; }
        public virtual DbSet<Block_Kafedra> Block_Kafedra { get; set; }
        public virtual DbSet<Block_Teachers> Block_Teachers { get; set; }
        public virtual DbSet<Calculation_Rules_Facility> Calculation_Rules_Facility { get; set; }
        public virtual DbSet<Calculation_Rules_Kafedra> Calculation_Rules_Kafedra { get; set; }
        public virtual DbSet<Category_Facility> Category_Facility { get; set; }
        public virtual DbSet<Category_Kafedra> Category_Kafedra { get; set; }
        public virtual DbSet<Category_Teachers> Category_Teachers { get; set; }
        public virtual DbSet<Comission> Comissions { get; set; }
        public virtual DbSet<Criteria_Facility> Criteria_Facility { get; set; }
        public virtual DbSet<Criteria_Kafedra> Criteria_Kafedra { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Kafedra> Kafedras { get; set; }
        public virtual DbSet<Mark_Facility> Mark_Facility { get; set; }
        public virtual DbSet<Mark_Kafedra> Mark_Kafedra { get; set; }
        public virtual DbSet<Mark_Teachers> Mark_Teachers { get; set; }
        public virtual DbSet<MarkTeachersCheck> MarkTeachersChecks { get; set; }
        public virtual DbSet<Position_Teachers> Position_Teachers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status_Doc_Facility> Status_Doc_Facility { get; set; }
        public virtual DbSet<Status_Doc_Kafedra> Status_Doc_Kafedra { get; set; }
        public virtual DbSet<Status_Doc_Teacher> Status_Doc_Teacher { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Сriteria_Teachers> Сriteria_Teachers { get; set; }
    }
}
