//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Facilities = new HashSet<Facility>();
            this.Kafedras = new HashSet<Kafedra>();
            this.Mark_Teachers = new HashSet<Mark_Teachers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public Nullable<int> Id_Kafedra { get; set; }
        public Nullable<int> Id_Position { get; set; }
        public bool Is_Staff { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<System.DateTime> d_b { get; set; }
        public Nullable<bool> vypusk { get; set; }
        public Nullable<System.DateTime> data_priema { get; set; }
        public int Staj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facility> Facilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kafedra> Kafedras { get; set; }
        public virtual Kafedra Kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark_Teachers> Mark_Teachers { get; set; }
        public virtual Position_Teachers Position_Teachers { get; set; }
        public virtual User User { get; set; }
    }
}
