//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityRating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сriteria_Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сriteria_Teachers()
        {
            this.Calculation_Rules_Kafedra = new HashSet<Calculation_Rules_Kafedra>();
            this.Mark_Teachers = new HashSet<Mark_Teachers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Mark { get; set; }
        public int Id_Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculation_Rules_Kafedra> Calculation_Rules_Kafedra { get; set; }
        public virtual Category_Teachers Category_Teachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark_Teachers> Mark_Teachers { get; set; }
    }
}
